AWSTemplateFormatVersion: "2010-09-09"
Description: "Custom Resource Stack to Retrieve Latest Amazon Linux 2 AMI"

Parameters:
  UniqueSuffix:
    Type: String
    Description: "Unique identifier for this deployment"

  AWSAccountId:
    Type: String
    Description: "Your AWS Account ID"

  Region:
    Type: String
    Default: "us-east-1"
    Description: "AWS region where AMI lookup will be performed"

  S3Bucket:
    Type: String
    Description: "S3 Bucket where CloudFormation templates are stored"

Resources:
  ## ✅ IAM Role for Lambda
  AmiLookupLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AmiLookupLambdaExecutionRole-${UniqueSuffix}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EC2DescribeImagesPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "ec2:DescribeImages"
                Resource: "*"

  ## ✅ Lambda Function to Fetch Latest AMI
  LatestAmiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "GetLatestAmazonLinuxAmi-${UniqueSuffix}"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt AmiLookupLambdaExecutionRole.Arn
      Timeout: 30
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: "ami-lookup-lambda.zip"

  ## ✅ Custom Resource
  AmiLookup:
    Type: Custom::AMI
    Properties:
      ServiceToken: !GetAtt LatestAmiLambdaFunction.Arn

Outputs:
  LatestAmazonLinuxAmi:
    Description: "Latest Amazon Linux 2 AMI ID"
    Value: !GetAtt AmiLookup.ImageId
