AWSTemplateFormatVersion: "2010-09-09"
Description: "Retrieves the latest Amazon Linux 2 AMI and provides it as an output"

Parameters:
  UniqueSuffix:
    Type: String
    Description: "Unique identifier for this deployment"

  AWSAccountId:
    Type: String
    Description: "Your AWS Account ID"

  Region:
    Type: String
    Default: "us-east-1"
    Description: "AWS region where AMI lookup will be performed"

Outputs:
  LatestAmazonLinuxAmi:
    Description: "Latest Amazon Linux 2 AMI ID"
    Value: !Ref LatestAmiId

Resources:
  ## ✅ Use AWS Systems Manager Parameter Store to Retrieve the Latest Amazon Linux 2 AMI ID
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
