AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys Twilio Webhook Lambda function"

Parameters:
  UniqueSuffix:
    Type: String
    Description: "Unique identifier for this deployment"

  AWSAccountId:
    Type: String
    Description: "Your AWS Account ID"

  Region:
    Type: String
    Default: "us-east-1"
    Description: "AWS region where resources will be deployed"

  S3Bucket:
    Type: String
    Description: "S3 Bucket where CloudFormation templates are stored"

  TwilioAccountSid:
    Type: String
    Description: "Twilio Account SID"

  TwilioAuthToken:
    Type: String
    Description: "Twilio Auth Token"

  TwilioPhoneNumber:
    Type: String
    Description: "Twilio Phone Number"

Resources:
  ## ✅ IAM Role for Lambda
  TwilioLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "TwilioLambdaExecutionRole-${UniqueSuffix}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "TwilioWebhookLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  ## ✅ Twilio Webhook Lambda Function
  TwilioWebhookLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "RegisterTwilioWebhook-${UniqueSuffix}"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt TwilioLambdaExecutionRole.Arn
      Timeout: 30
      Environment:
        Variables:
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: "twilio-webhook-lambda.zip"

  ## ✅ Wait Condition Handle for CloudFormation
  TwilioWebhookWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  ## ✅ Wait Condition to Ensure Lambda Completes Before Stack Proceeds
  TwilioWebhookWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: !Ref TwilioWebhookWaitHandle
      Timeout: "300"
    DependsOn: TwilioWebhookLambda

Outputs:
  TwilioWebhookLambdaArn:
    Description: "ARN of the Twilio Webhook Lambda function"
    Value: !GetAtt TwilioWebhookLambda.Arn
